version: '3'
services:
  web:
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    image: build2024/web:latest
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://api:9000
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari_network


  api:
    image: build2024/app:latest
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari_network
      
networks:
  mercari-network:
    driver: bridge