FROM node:20-alpine

WORKDIR /app

ENV REACT_APP_API_URL=http://api:9000
ENV FRONT_URL=http://localhost:3000

COPY package.json . 
COPY package-lock.json . 
RUN npm install
COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]